// @ts-check
import tseslint from 'typescript-eslint';
import tsdocPlugin from 'eslint-plugin-tsdoc';
import jsdoc from 'eslint-plugin-jsdoc';
import prettierConfig from 'eslint-config-prettier';

export default tseslint.config(
  // ── Global ignores ────────────────────────────────────────────────────────
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'coverage/**',
      'src/infrastructure/db/migrations/**', // generated by drizzle-kit
      // Root-level tool configs — not source, no TSDoc/JSDoc required
      '.dependency-cruiser.cjs',
      'commitlint.config.cjs',
      'postcss.config.mjs',
    ],
  },

  // ── TypeScript — strict preset (no type-project required at Stage 0) ──────
  ...tseslint.configs.strict,

  // ── TSDoc + jsdoc rules ───────────────────────────────────────────────────
  {
    plugins: {
      tsdoc: tsdocPlugin,
      jsdoc,
    },
    settings: {
      jsdoc: { mode: 'typescript' },
    },
    rules: {
      // Validate syntax of existing TSDoc comments
      'tsdoc/syntax': 'error',

      // Require TSDoc on every exported symbol (DOCUMENTATION.md mandate)
      'jsdoc/require-jsdoc': [
        'error',
        {
          publicOnly: true,
          require: {
            FunctionDeclaration: true,
            MethodDefinition: true,
            ClassDeclaration: true,
            ArrowFunctionExpression: false,
            FunctionExpression: false,
          },
          // TypeScript-specific declaration forms
          contexts: ['TSInterfaceDeclaration', 'TSTypeAliasDeclaration', 'TSEnumDeclaration'],
        },
      ],

      // Require @param and @returns only when present in signature
      'jsdoc/require-param': ['error', { enableFixer: false, checkDestructured: false }],
      'jsdoc/require-returns': ['error', { enableFixer: false, checkGetters: false }],
      'jsdoc/require-param-description': 'error',
      'jsdoc/require-returns-description': 'warn',

      // TSDoc tag spelling (tsdoc/syntax already handles unknown tags, this adds completeness)
      'jsdoc/check-tag-names': ['error', { typed: true }],
    },
  },

  // ── Prettier — must be last, disables conflicting rules ──────────────────
  prettierConfig,
);
