ALTER TABLE "participants" ADD CONSTRAINT "participants_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "invitation" TO tenantkit_app USING ("organizationId" = current_setting('app.current_tenant', true)::uuid) WITH CHECK ("organizationId" = current_setting('app.current_tenant', true)::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "member" TO tenantkit_app USING ("organizationId" = current_setting('app.current_tenant', true)::uuid) WITH CHECK ("organizationId" = current_setting('app.current_tenant', true)::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "events" TO tenantkit_app USING (tenant_id = current_setting('app.current_tenant', true)::uuid) WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "pricing_tiers" TO tenantkit_app USING (tenant_id = current_setting('app.current_tenant', true)::uuid) WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "participants" TO tenantkit_app USING (tenant_id = current_setting('app.current_tenant', true)::uuid) WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "payments" TO tenantkit_app USING (tenant_id = current_setting('app.current_tenant', true)::uuid) WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "registrations" TO tenantkit_app USING (tenant_id = current_setting('app.current_tenant', true)::uuid) WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "tenant_entitlements" TO tenantkit_app USING (tenant_id = current_setting('app.current_tenant', true)::uuid) WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "audit_log" TO tenantkit_app USING (tenant_id = current_setting('app.current_tenant', true)::uuid) WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "consent_records" TO tenantkit_app USING (tenant_id = current_setting('app.current_tenant', true)::uuid) WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);