import type { Result } from '@shared/result';
import type { DomainError, NotFoundError } from '@shared/errors';
import type { Email } from '@domain/value-objects/email';
import type { PhoneNumber } from '@domain/value-objects/phone-number';
import type { TenantId } from '@domain/value-objects/tenant-id';

/**
 * Read model for a persisted participant, as returned by the repository.
 *
 * @remarks
 * All value-object fields are already validated. `userId` is nullable because
 * guests may register without a platform account (ADR 0004).
 */
export interface ParticipantRecord {
  /** UUIDv4 generated by `IdPort` before the first `save()` call. */
  readonly id: string;
  /** Tenant this participant belongs to. */
  readonly tenantId: TenantId;
  readonly firstName: string;
  readonly lastName: string;
  readonly email: Email;
  /** Optional — not all participants provide a phone number. */
  readonly phone?: PhoneNumber;
  /** Link to the Better Auth `user` record; absent for guest registrations. */
  readonly userId?: string;
  readonly createdAt: Date;
  readonly updatedAt: Date;
}

/**
 * Driven port — participant persistence.
 *
 * @remarks
 * Implementations are provided by infrastructure adapters:
 * `DrizzleParticipantRepository` for production (enforced by RLS),
 * `InMemoryParticipantRepository` for unit and integration tests.
 * Use-cases depend on this interface, never on a concrete adapter (ADR 0001).
 */
export interface ParticipantRepositoryPort {
  /**
   * Finds a participant by their UUID, scoped to the given tenant.
   *
   * @param id - The participant's UUIDv4.
   * @param tenantId - The tenant scope; cross-tenant lookups always return NotFoundError.
   * @returns The participant record, or `NotFoundError` if absent for this tenant.
   */
  findById(id: string, tenantId: TenantId): Promise<Result<ParticipantRecord, NotFoundError>>;

  /**
   * Looks up a participant by email within the given tenant.
   *
   * @param email - The email to search for.
   * @param tenantId - The tenant scope.
   * @returns `null` when no match is found; `DomainError` only on infrastructure failure.
   */
  findByEmail(
    email: Email,
    tenantId: TenantId,
  ): Promise<Result<ParticipantRecord | null, DomainError>>;

  /**
   * Persists a participant record (insert or update by primary key).
   *
   * @param record - The full record to write; the `id` field is the upsert key.
   * @returns `ok(void)` on success, or `DomainError` on infrastructure failure.
   */
  save(record: ParticipantRecord): Promise<Result<void, DomainError>>;

  /**
   * Removes a participant from the tenant's data store.
   *
   * @param id - The participant's UUIDv4.
   * @param tenantId - The tenant scope.
   * @returns `ok(void)` on success, or `NotFoundError` if the record does not exist.
   */
  delete(id: string, tenantId: TenantId): Promise<Result<void, NotFoundError>>;
}
